Added release notes section to guide
riganti/dotvvm-docs pull request #110
Opened 2021-04-17 09:18 UTC by MichalTichy

2021-05-29 13:58 UTC, tomasherceg requested changes

2021-05-29 13:58 UTC, tomasherceg commented on GUIDE.md
> +Sections should be level 1 headings `# New features` while individual entries should be level 3 headings `### Cool new feature`.
I am not sure about Heading 1 here - for framework release notes, I am using heading 2.

2021-05-29 13:58 UTC, tomasherceg commented on GUIDE.md
> +- Version — level 1
I think that each page should have only one H1 (which is Release Notes in our case). 
Therefore, I'd prefer shifting the titles to use H2, H3 and H4. 
What do you think?

2021-05-29 13:58 UTC, tomasherceg commented on GUIDE.md
> +- ### [```Icon```](https://www.dotvvm.com/docs/controls/bootstrap4/Icon)
For inline blocks of code, one backtick is just enough. Three backticks are used for code blocks.
Also, if the name is also a link, I think we don't need to use backticks there as the word is highlighted anyway. This is how it's done everywhere else in the docs.

2021-05-29 14:10 UTC, MichalTichy commented on GUIDE.md
> +- Version — level 1
If we plan to keep the page title Release notes than I would shift it.
I would prefer not to have the page title for the release notes because it is unnecessary.  There is no text between this heading and the subheading so having it in the side menu is not helpful.

2021-05-29 14:12 UTC, MichalTichy commented on GUIDE.md
> +Sections should be level 1 headings `# New features` while individual entries should be level 3 headings `### Cool new feature`.
I've described the reasoning in [the other comment regarding the title levels](https://github.com/riganti/dotvvm-docs/pull/110/files#r641943158).

2021-05-29 14:23 UTC, MichalTichy commented on GUIDE.md
> +Sections should be level 1 headings `# New features` while individual entries should be level 3 headings `### Cool new feature`.
The reason why I've chosen the weird combination of level 1 and level 3 is readability.
In my opinion it`s easier to scroll through while searching for the next section (improvements, bug fixes , ...) when the individual changes and the section titles are as distinct as possible.
Even with the combination of H1 + H3 the distinction is not as good as I would want it to be.
H1 + H3
![image](https://user-images.githubusercontent.com/5333577/120073744-f6ea1f80-c099-11eb-94e2-ca4c32c494bb.png)

H2 + H3
![image](https://user-images.githubusercontent.com/5333577/120073776-13865780-c09a-11eb-9f7b-197a7bc8673a.png)

2021-05-29 14:27 UTC, MichalTichy commented on GUIDE.md
> +- ### [```Icon```](https://www.dotvvm.com/docs/controls/bootstrap4/Icon)
Agreed.
I've removed this from all links and kept single tick for places where some control is mentioned.

2021-05-29 14:28 UTC, MichalTichy commented on GUIDE.md
> +Sections should be level 1 headings `# New features` while individual entries should be level 3 headings `### Cool new feature`.
I'll leave this decision up to you @tomasherceg .

2021-06-01 07:04 UTC, tomasherceg commented on GUIDE.md
> +Sections should be level 1 headings `# New features` while individual entries should be level 3 headings `### Cool new feature`.
Since the docs are displayed on our website, we can adjust our CSS to make it as readable as possible. We've took inspiration from Microsoft docs for the styling, so I assume they focused on this problem too. 

Also, Google penalizes pages that don't have the correct headings structure, so I'd prefer sticking to Level 1 for Release notes (that's the name of the page, it's shown in the menu), Level 2 for version numbers, and Level 3 for New features, Bug fixes, and Level 4 for the name of the feature.

Alternatively, we can omit Level 4 headings and just put the feature title in bold. I believe I've already used that in DotVVM release notes:

```
* #83 **Added this new awesome feature**. Thanks to this, you can now write less code.
```

The docs site also shows the table of contents on the right side, and it will also work well with this structure.

2021-06-03 10:31 UTC, MichalTichy commented on GUIDE.md
> +Sections should be level 1 headings `# New features` while individual entries should be level 3 headings `### Cool new feature`.
This is release notes for DotVVM. I thought that those are displayed only at Github :O

2021-06-23 07:38 UTC, MichalTichy commented on GUIDE.md
> +- Version — level 1
We have decided to keep page title and thus the levels would be shifted down.

2021-06-23 09:16 UTC, MichalTichy commented on GUIDE.md
> +Sections should be level 1 headings `# New features` while individual entries should be level 3 headings `### Cool new feature`.
We have decided to stick to H2 + H3

2021-06-23 09:17 UTC, merged