Comprehensive fix of misspellings and typos
riganti/dotvvm-docs pull request #117
Opened 2021-06-14 15:57 UTC by JosefPihrt

fixes #116 

This PR contains comprehensive fix of misspellings/typos + US english is preferred.

I'm not sure about doc.xml files. If these files are generated from source files it probably should not be included.

2021-06-14 16:16 UTC, JosefPihrt commented
There are some errors for which I was not able to find the fix:
```
bave
  dotvvm-docs\Controls\bootstrap4\CardBody\sample2\sample.md
    * `p` and other text elements should >>>bave<<< `card-text` CSS class.
incusing
  dotvvm-docs\Controls\builtin\doc.xml
                Writes this code >>>incusing<<< parameters to the ParametrizedCode.Builder
```

2021-06-15 07:58 UTC, MichalTichy commented
Hi,
this looks awesome. I'll try to go through this today/tomorrow.

2021-06-16 09:01 UTC, MichalTichy commented on Controls/builtin/doc.xml
> +        <member name="T:DotVVM.Framework.Binding.Properties.CastExpressionBindingProperty">
This is part of the public API, changing it would be hard to do.
```suggestion
        <member name="T:DotVVM.Framework.Binding.Properties.CastedExpressionBindingProperty">
```

2021-06-16 09:10 UTC, MichalTichy commented on Controls/businesspack/ColorPicker/sample5/page.dothtml
> +        <bp:Icon Icon="Palette"></bp:Icon>
This represents painters Pallete icon.
 ```suggestion
        <bp:Icon Icon="Pallete"></bp:Icon>
```

2021-06-16 09:10 UTC, MichalTichy commented on Controls/businesspack/ColorPicker/sample5/sample.md
> +* `ToggleIcon` represents an icon that opens the popup with color scale and predefined colors. The default is `Palette` icon.
This represents painters palette icon.
```suggestion
* `ToggleIcon` represents an icon that opens the popup with color scale and predefined colors. The default is `Pallete` icon.
```

2021-06-16 09:11 UTC, MichalTichy commented on Controls/businesspack/Icon/control.md
> +		<title>Palette</title>
This represents painters palette.
```suggestion
		<title>Pallete</title>
```

2021-06-16 09:17 UTC, MichalTichy requested changes
Apart from few corrections which are part of public API (and cannot be changed) it is OK.

2021-06-16 09:25 UTC, MichalTichy commented
> There are some errors for which I was not able to find the fix:
> 
> ```
> bave
>   dotvvm-docs\Controls\bootstrap4\CardBody\sample2\sample.md
>     * `p` and other text elements should >>>bave<<< `card-text` CSS class.
> incusing
>   dotvvm-docs\Controls\builtin\doc.xml
>                 Writes this code >>>incusing<<< parameters to the ParametrizedCode.Builder
> ```

I've fixed those directly in 3.0 or created PR.

2021-06-16 09:42 UTC, MichalTichy commented on menu.xml
> +    <DocPageMenuItem RouteName="release-notes" PageName="Release notes" LegacyPaths="commercial-business-pack-release-notes" />
This is needed for old links.
```suggestion
    <DocPageMenuItem RouteName="release-notes" PageName="Release notes" LegacyPaths="commecial-business-pack-release-notes" />
```

2021-06-16 10:37 UTC, MichalTichy commented on Controls/builtin/doc.xml
> +            <param name="includingThis">Returns also the caller control</param>
Unfortunately this is typo in public API.

```suggestion
            <param name="incudingThis">Returns also the caller control</param>
```

2021-06-16 10:47 UTC, MichalTichy approved these changes

2021-06-16 10:47 UTC, merged